/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.frontend;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;

/**
 *
 * @author luedu
 */
public class Bienvenida extends javax.swing.JFrame {

    /**
     * Creates new form Bienvenida
     */
    public Bienvenida() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jName = new javax.swing.JLabel();
        jversion = new javax.swing.JLabel();
        jUser = new javax.swing.JLabel();
        jCarnet = new javax.swing.JLabel();
        jBManual = new javax.swing.JButton();
        jBAnalizador = new javax.swing.JButton();
        jBExit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jName.setBackground(new java.awt.Color(102, 255, 102));
        jName.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        jName.setForeground(new java.awt.Color(51, 255, 51));
        jName.setText("\"Analizador Léxico\"");
        jName.setAutoscrolls(true);
        getContentPane().add(jName, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, -1));

        jversion.setBackground(new java.awt.Color(102, 255, 102));
        jversion.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jversion.setForeground(new java.awt.Color(51, 255, 51));
        jversion.setText(" V: 1.1.1 ");
        jversion.setAutoscrolls(true);
        getContentPane().add(jversion, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, -1, -1));

        jUser.setBackground(new java.awt.Color(255, 255, 0));
        jUser.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jUser.setForeground(java.awt.Color.red);
        jUser.setText("Luis Eduardo Guillén Ruiz");
        jUser.setAutoscrolls(true);
        getContentPane().add(jUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, -1, -1));

        jCarnet.setBackground(new java.awt.Color(102, 255, 102));
        jCarnet.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jCarnet.setForeground(java.awt.Color.red);
        jCarnet.setText("201744792");
        jCarnet.setAutoscrolls(true);
        getContentPane().add(jCarnet, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, -1, -1));

        jBManual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/images.png"))); // NOI18N
        jBManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBManualActionPerformed(evt);
            }
        });
        getContentPane().add(jBManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 140, -1));

        jBAnalizador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/compilador-icono.png"))); // NOI18N
        jBAnalizador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAnalizadorActionPerformed(evt);
            }
        });
        getContentPane().add(jBAnalizador, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 500, 130, 130));

        jBExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/exit.png"))); // NOI18N
        jBExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExitActionPerformed(evt);
            }
        });
        getContentPane().add(jBExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 500, 140, 130));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ing CUNOC.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, 0, 340, 270));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/WallpaperIz.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExitActionPerformed
        System.exit (0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jBExitActionPerformed

    private void jBAnalizadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAnalizadorActionPerformed
        this.setVisible(false); 
        new Analizador().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jBAnalizadorActionPerformed

    private void jBManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBManualActionPerformed
         try {
            File path;
            path = new File ("C:\\Users\\luedu\\Desktop\\LEGR_P2\\Analizador Lexico\\Manual Técnico P_2, LEGR.docx");
            Desktop.getDesktop().open(path);
        }catch (IOException ex) {
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jBManualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bienvenida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAnalizador;
    private javax.swing.JButton jBExit;
    private javax.swing.JButton jBManual;
    private javax.swing.JLabel jCarnet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jName;
    private javax.swing.JLabel jUser;
    private javax.swing.JLabel jversion;
    // End of variables declaration//GEN-END:variables
}
